version: "3.9"

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__ZOMBIE_TASK_THRESHOLD: 600
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 120
    DATABASE_URL: postgresql://daudsaid:9848@host.docker.internal:5433/fraud_db
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../etl:/opt/airflow/etl
    - ../dbt:/opt/airflow/dbt
    - ../data:/opt/airflow/data
    - ../requirements.txt:/opt/airflow/requirements.txt
  depends_on:
    airflow-postgres:
      condition: service_healthy
  deploy:
    resources:
      limits:
        memory: 3g

services:
  airflow-postgres:
    image: postgres:15
    container_name: fraud-airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5434:5432"

  airflow-init:
    <<: *airflow-common
    container_name: fraud-airflow-init
    command: version
    entrypoint: /bin/bash -c "airflow db init && airflow users create --username admin --password admin --firstname Daud --lastname Abdi --role Admin --email daudsaidabdi@gmail.com"

  airflow-webserver:
    <<: *airflow-common
    container_name: fraud-airflow-webserver
    command: webserver
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      retries: 3

  airflow-scheduler:
    <<: *airflow-common
    container_name: fraud-airflow-scheduler
    command: scheduler
